### ISSUE TITLE
使用橡皮后再移动原图层会使橡皮不生效，这个怎么解决？还有就是能把各个工具能设置的属性文档给我一份吗？

### ISSUE THREAD

**Issue by Voka-wjl** [ybx13579/zwibbler-drawBoard#1]

**Comment by ybx13579** [comment]
您好， 他这个橡皮好像就是用画笔模拟的，不是真的删除了，你可以看看他的英文文档，我文章里写的只是我用到的一些可以定制的属性，也不是很全。API地址 ：http://zwibbler.com/docs/

**Comment by Dragonwjl** [comment]
那橡皮这块你有什么好的解决办法能分享一下吗？

**Comment by ybx13579** [comment]
现在做的我都把橡皮功能隐藏了，再别的方法你可以给作者发邮件看他有没有什么方法吧，不过他有可能会问你有没有买他的定制产品。橡皮功能你可以跟部门人沟通下看看可不可以放弃，我当初用这个是需要用到圈和箭头，如果你们产品不太需要可以用简单的canvas画笔编辑功能就好了，没帮到你真不好意思

**Comment by Dragonwjl** [comment]
那我再问问吧，这块功能是肯定要的，谢谢你的回答

**Comment by Dragonwjl** [comment]
对了，你有作者的联系方式吗？？

**Comment by ybx13579** [comment]
zwibbler作者邮箱：steve.hanov@gmail.com

**Comment by ybx13579** [comment]
@如果您解决了可以告知我一声解决方法，我更新上去，谢 ◕ᴗ◕

**Comment by Dragonwjl** [comment]
好的
